#!/bin/bash -e
# LIME main driver script
# This file is part of LIME, the versatile line modeling engine
#
# Copyright (C) 2006-2014 Christian Brinch
# Copyright (C) 2015-2017 The LIME development team
# Copyright (C) 2023 mkirc"

export PATHTOLIME=$( cd  -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# load command line arguments
. "$PATHTOLIME"/lime-opt.sh

# default initialization - optionals
cpp_flags=""
verbose="yes"
do_test="no"
usehdf5="no"

set_nthreads() {
    if [[ "$_arg_nthreads" -gt 1 ]]; then
        cpp_flags+="-DNTHREADS=${_arg_nthreads} "
    else
        die "error: invalid number of threads"
    fi
}

[[ "$_arg_hdf5" == "on" ]] && usehdf5="yes"
[[ "$_arg_fast" == "on" ]] && cpp_flags+="-DFASTEXP "
[[ "$_arg_ncurses" == "off" ]] && cpp_flags+="-DNO_NCURSES "
[[ "$_arg_silent" == "on" ]] && verbose="no"
[[ "$_arg_debug" == "on" ]] && do_test="yes"
[[ -n "$_arg_nthreads" ]] && set_nthreads

# Set up the PATHTOLIME, LD_LIBRARY_PATH and WORKDIR variables
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PATHTOLIME}/lib
export WORKDIR=$PWD

# change into lime dir
pushd ${PATHTOLIME} >> /dev/null
# Compile the code
make -s EXTRACPPFLAGS="${cpp_flags}" \
    MODELS=$WORKDIR/"$_arg_model_file" \
    TARGET=$WORKDIR/lime_$$.x \
    DOTEST=$do_test \
    VERBOSE=$verbose \
    USEHDF5=$usehdf5
make -s limeclean

# change into workdir
popd >> /dev/null

if [[ "$_arg_compile_only" == "off" ]]; then
    # Run the code
    ./lime_$$.x

    # remove the executable
    [[ -e ./lime_$$.x ]] && rm -rf lime_$$.x
fi

exit 0
