version: "3.9"

services:
  lime-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lime-dev
    container_name: lime-dev
    hostname: lime-dev
  lime:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: lime
    container_name: lime
    hostname: lime
