#!/bin/bash

_base_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

readonly LIME_DIR=/lime
readonly DEFS_FILE="$LIME_DIR"/Makefile.defs
readonly CONFIGURE="$LIME_DIR"/configure
readonly MODEL_DIR=/model

trap cleanup SIGINT
trap cleanup SIGTERM
trap cleanup ERR

cleanup() {
    # lime tries to 'make -s limeclean' after compilation,
    # but this also handles a user hitting CTRL-C
    # mid-compilation
    for f in "$MODEL_DIR"/lime_*.x; do
        [[ -e "$f" ]] && rm "$f"
    done
}

run_configure() {
    # if Makefile.defs does not exist or is older than ./configure,
    # run ./configure first.
    if [[ ! -e "$DEFS_FILE" ]] || [[ "$DEFS_FILE" -ot "$CONFIGURE"  ]]; then
        bash "$CONFIGURE"
        return $?
    fi
    return 0
}

if [[ -x "$LIME_DIR"/lime ]]; then
    run_configure

    cd "$MODEL_DIR" || exit # test if default model dir exists
    if [[ $# -eq 0 ]]; then # no command line options
        bash "$LIME_DIR"/lime --no-ncurses ./model.c
        LIME_EXIT_STATUS=$?
    else
        bash "$LIME_DIR"/lime "$@"
        LIME_EXIT_STATUS=$?
    fi
    cleanup
    exit $LIME_EXIT_STATUS
else
    echo "lime script not found (in "$LIME_DIR")."
    exit 3
fi

